name: Run Gradle Build

on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename built JAR
        run: |
          ORIGINAL_JAR=$(find build/libs -name "*.jar" | head -n 1)
          TARGET_JAR="build/libs/zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar"
          mv "$ORIGINAL_JAR" "$TARGET_JAR"

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: zen-1.8.9-forge-dev-${{ github.run_number }}
          path: build/libs/zen-1.8.9-forge-dev-${{ github.run_number }}.jar

  send-to-discord:
    if: github.event_name == 'push'
    needs: gradle
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: zen-1.8.9-forge-dev-${{ github.run_number }}
          path: ./artifact

      - name: Send jar to Discord
        run: |
          JAR_FILE="./artifact/zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar"
          echo "Uploading $JAR_FILE to Discord..."
          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "payload_json={\"content\":\"Zen 1.8.9 dev build!\"}" \
            -F "file=@${JAR_FILE}" \
            "$DISCORD_WEBHOOK_URL"
